spring.config.import=optional:classpath:application-secrets.properties

# Server
server.port=8080

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/depthon_db
spring.datasource.username=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# App name
spring.application.name=depthon-core

# JWT expiration (NOT secret - just 24 hours in milliseconds)
jwt.expiration=86400000

# Redis connection
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Cache type
spring.cache.type=redis

# Cache entries expire after 60 seconds
spring.cache.redis.time-to-live=60000

# Kafka connection
spring.kafka.bootstrap-servers=localhost:9092

# Producer settings (how we SEND messages)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Consumer settings (how we RECEIVE messages)
spring.kafka.consumer.group-id=depthon-judging-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest